name: sirshannon
favicon: null
layout_spectrum: 0.4807073725387454
typography_spectrum: 0.9455895340070128
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8481667889282107
  lightness: 0.687499986961484
  saturation: 0.6451670685783029
  rhythmicContrast: 0.1429910168517381
purpose: []
